import Head from "next/head";
import SideNavbar from "../components/SideNavbar";
import FilterRow from "@/components/analytics/FilterRow";
import StatsRow from "@/components/analytics/StatsRow";
import TotalJobPostGraph from "@/components/analytics/TotaljobPostGraph";
import TotalApplicantsGraph from "@/components/analytics/TotalApllicantsGraph";
import ComparisonGraph from "@/components/analytics/ComparisionGraph";
export default function Home() {
  return (
    <div className="bg-gray-50">
      <Head>
        <title>Responsive Side-Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="flex flex-col">
      {/* 1st Row */}
      <FilterRow />

      {/* 2nd Row */}
      <StatsRow />

      {/* 3rd Row */}
      {/* <TotalJobPostGraph /> */}
      {/* <TotalApplicantsGraph /> */}

      {/* 4th Row */}
      {/* <ComparisonGraph /> */}
    </div>
    </div>
  );
}